//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IEDBContext : DbContext
    {
        public IEDBContext()
            : base("name=IEDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth_Module> Auth_Module { get; set; }
        public virtual DbSet<Auth_ModulePermission> Auth_ModulePermission { get; set; }
        public virtual DbSet<Auth_Permission> Auth_Permission { get; set; }
        public virtual DbSet<Auth_Role> Auth_Role { get; set; }
        public virtual DbSet<Auth_RoleModulePermission> Auth_RoleModulePermission { get; set; }
        public virtual DbSet<Authen_UserArea> Authen_UserArea { get; set; }
        public virtual DbSet<Authen_UserRole> Authen_UserRole { get; set; }
        public virtual DbSet<SysConfig_OperateLog> SysConfig_OperateLog { get; set; }
        public virtual DbSet<T_Areas> T_Areas { get; set; }
        public virtual DbSet<T_CurveLibrary> T_CurveLibrary { get; set; }
        public virtual DbSet<T_Datas> T_Datas { get; set; }
        public virtual DbSet<T_DeviceCurveLibrary> T_DeviceCurveLibrary { get; set; }
        public virtual DbSet<T_DeviceMaintenances> T_DeviceMaintenances { get; set; }
        public virtual DbSet<T_Devices> T_Devices { get; set; }
        public virtual DbSet<T_History> T_History { get; set; }
        public virtual DbSet<T_SysSettings> T_SysSettings { get; set; }
        public virtual DbSet<T_TimeSpanSettings> T_TimeSpanSettings { get; set; }
        public virtual DbSet<T_Users> T_Users { get; set; }
    }
}
