//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Areas
    {
        public T_Areas()
        {
            this.Authen_UserArea = new HashSet<Authen_UserArea>();
            this.T_Areas1 = new HashSet<T_Areas>();
            this.T_Devices = new HashSet<T_Devices>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsLeaf { get; set; }
        public Nullable<int> CreateId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyId { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
    
        public virtual ICollection<Authen_UserArea> Authen_UserArea { get; set; }
        public virtual ICollection<T_Areas> T_Areas1 { get; set; }
        public virtual T_Areas T_Areas2 { get; set; }
        public virtual ICollection<T_Devices> T_Devices { get; set; }
    }
}
