//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Datas
    {
        public int Id { get; set; }
        public int DeviceId { get; set; }
        public System.DateTime DataTime { get; set; }
        public Nullable<decimal> OutdoorTemp { get; set; }
        public Nullable<decimal> SupplyWaterTemp1 { get; set; }
        public Nullable<decimal> SupplyWaterTemp2 { get; set; }
        public Nullable<decimal> BackWaterTemp1 { get; set; }
        public Nullable<decimal> BackWaterTemp2 { get; set; }
        public Nullable<decimal> FixWaterTemp1 { get; set; }
        public Nullable<decimal> FixWaterTemp2 { get; set; }
        public Nullable<int> Valve1 { get; set; }
        public Nullable<int> Valve2 { get; set; }
        public int WirelessStatus { get; set; }
        public int WorkStatus { get; set; }
        public Nullable<int> WaterNetStatus1 { get; set; }
        public Nullable<int> WaterNetStatus2 { get; set; }
        public byte[] Data27 { get; set; }
        public byte[] Data28 { get; set; }
        public byte[] Data29 { get; set; }
        public byte[] Data30 { get; set; }
        public Nullable<int> CreateId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyId { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual T_Devices T_Devices { get; set; }
    }
}
