//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Devices
    {
        public T_Devices()
        {
            this.T_Datas = new HashSet<T_Datas>();
            this.T_DeviceCurveLibrary = new HashSet<T_DeviceCurveLibrary>();
            this.T_DeviceMaintenances = new HashSet<T_DeviceMaintenances>();
            this.T_History = new HashSet<T_History>();
        }
    
        public int Id { get; set; }
        public string DeviceCode { get; set; }
        public string DeviceName { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public int CtrlMode { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<System.DateTime> InstallTime { get; set; }
        public string Memo { get; set; }
        public Nullable<int> WorkMode { get; set; }
        public Nullable<int> SaveInterval { get; set; }
        public Nullable<int> CtrlNumber { get; set; }
        public bool IsInited { get; set; }
        public Nullable<decimal> OutdoorFix { get; set; }
        public Nullable<decimal> SupplyWaterFix1 { get; set; }
        public Nullable<decimal> SupplyWaterFix2 { get; set; }
        public Nullable<decimal> BackFix1 { get; set; }
        public Nullable<decimal> BackFix2 { get; set; }
        public Nullable<decimal> FixWater1 { get; set; }
        public Nullable<decimal> FixWater2 { get; set; }
        public bool IsOnline { get; set; }
        public Nullable<int> CreateId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyId { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
    
        public virtual T_Areas T_Areas { get; set; }
        public virtual ICollection<T_Datas> T_Datas { get; set; }
        public virtual ICollection<T_DeviceCurveLibrary> T_DeviceCurveLibrary { get; set; }
        public virtual ICollection<T_DeviceMaintenances> T_DeviceMaintenances { get; set; }
        public virtual ICollection<T_History> T_History { get; set; }
    }
}
